import { NextResponse } from "next/server";
import {
  buildAssistantInstructions,
  detectAssistantLanguageStyle,
  type AssistantMessage,
} from "@/lib/ai";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import type { AssistantChatRequest } from "@/types";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

const MAX_MESSAGE_LENGTH = 2_000;
const MAX_HISTORY_MESSAGES = 10;
const GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions";

function isAssistantMessage(value: unknown): value is AssistantMessage {
  if (!value || typeof value !== "object") return false;

  const message = value as Record<string, unknown>;

  return (
    (message.role === "user" || message.role === "assistant") &&
    typeof message.content === "string" &&
    message.content.trim().length > 0 &&
    message.content.length <= MAX_MESSAGE_LENGTH
  );
}

export async function POST(request: Request) {
  const apiKey = process.env.GROQ_API_KEY;

  if (!apiKey) {
    return NextResponse.json(
      {
        error: "AI_SERVICE_NOT_CONFIGURED",
        message:
          "Groq API key is not configured. Please set GROQ_API_KEY in your environment variables.",
      },
      { status: 503 }
    );
  }

  const supabase = await createServerSupabaseClient();

  if (supabase) {
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json(
        { error: "UNAUTHORIZED", message: "Authentication required." },
        { status: 401 }
      );
    }
  }

  let body: AssistantChatRequest;

  try {
    body = await request.json();
  } catch {
    return NextResponse.json(
      { error: "INVALID_REQUEST", message: "Malformed JSON payload in request." },
      { status: 400 }
    );
  }

  const messages = Array.isArray(body.messages)
    ? body.messages
        .filter(isAssistantMessage)
        .slice(-MAX_HISTORY_MESSAGES)
    : [];

  const latestUserMessage = [...messages]
    .reverse()
    .find((message) => message.role === "user");

  if (!latestUserMessage) {
    return NextResponse.json(
      { error: "INVALID_REQUEST", message: "No user message found in conversation history." },
      { status: 400 }
    );
  }

  try {
    const languageStyle = detectAssistantLanguageStyle(
      latestUserMessage.content
    );

    const systemInstructions = buildAssistantInstructions(
      body.context,
      languageStyle
    );

    const groqModel = process.env.GROQ_MODEL || "openai/gpt-oss-120b";

    const groqPayload = {
      model: groqModel,
      messages: [
        {
          role: "system",
          content: systemInstructions,
        },
        ...messages.map((msg) => ({
          role: msg.role === "assistant" ? "assistant" : "user",
          content: msg.content,
        })),
      ],
      temperature: 0.6,
      max_tokens: 1000,
    };

    const groqResponse = await fetch(GROQ_API_URL, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey.trim()}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(groqPayload),
    });

    if (!groqResponse.ok) {
      const errorData = await groqResponse.json().catch(() => null);
      const errorMsg =
        errorData?.error?.message ||
        `Groq API responded with status ${groqResponse.status}`;

      console.error("[WeatherGPT Assistant] Groq API error:", {
        status: groqResponse.status,
        error: errorMsg,
      });

      let userFriendly =
        "The AI assistant is temporarily unavailable. Please try again in a moment.";

      if (groqResponse.status === 401) {
        userFriendly = "Groq API authentication failed. Please verify your GROQ_API_KEY.";
      } else if (groqResponse.status === 429) {
        userFriendly =
          "Groq API rate limit reached. Please wait a few moments before sending another message.";
      } else if (groqResponse.status === 404 || errorMsg.includes("model")) {
        userFriendly = `The configured Groq model (${groqModel}) is unavailable.`;
      }

      return NextResponse.json(
        {
          error: "AI_SERVICE_UNAVAILABLE",
          message: userFriendly,
        },
        { status: 502 }
      );
    }

    const result = await groqResponse.json();
    const assistantText = result?.choices?.[0]?.message?.content?.trim();

    if (!assistantText) {
      return NextResponse.json(
        {
          error: "INVALID_AI_RESPONSE",
          message: "Empty response generated by AI assistant.",
        },
        { status: 502 }
      );
    }

    return NextResponse.json({
      message: assistantText,
    });
  } catch (error) {
    console.error("[WeatherGPT Assistant] Assistant request failed:", error);

    const errStr = error instanceof Error ? error.message : String(error);

    return NextResponse.json(
      {
        error: "AI_SERVICE_UNAVAILABLE",
        message:
          "Unable to connect to the WeatherGPT intelligence service. Please try again in a moment.",
        details: errStr,
      },
      { status: 502 }
    );
  }
}